logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  port: 8000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/sport_project?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    user:
      name: root
      password: 12345

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #Cloudinary config
cloudinary:
  api-key: 316856437928724
  api-secret: ${CLOUDINARY_SECRET}
  cloud-name: dncft9rby